model:
    arch: fcn8s
data:
    dataset: camvid
    train_split: train
    val_split: val
    img_rows: 1354
    img_cols: 380
    path: C:/zaloopa/data/result_sosi
    sbd_path: C:/zaloopa/data/result_sosi
training:
    train_iters: 300000
    batch_size: 1
    val_interval: 2000
    n_workers: 1
    print_interval: 5
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: fcn8s_pascal_best_model.pkl
